##INSTRUCTIONS::: Command used in the terminal --- python3 Tester.py(macbook) and based on the messages and destinations generated by the TA(given) ,we will take the input manually through the code in the line no -- 368 in the code for all the laptops (2) in which we are testing.

import time
import pyaudio
import threading
from datetime import datetime
import numpy as np
import random
from queue import Queue
from scipy.fft import fft

F_0 = 4000
F_1 = 5000
F_NULL = 6000
BIT_RATE = 12
FS = 44100
DURATION_PER_BIT = 1 / BIT_RATE
FORMAT = pyaudio.paFloat32
CHANNELS = 1
CHUNK = int(FS * DURATION_PER_BIT)
epsilon = 30 #for extracting frequencies that got deviated due to noise

def detect_frequency(signal):
    signal_fft = fft(signal)
    freqs = np.fft.fftfreq(len(signal_fft), 1 / FS)
   
    peak_freq = abs(freqs[np.argmax(np.abs(signal_fft))])
    return peak_freq

def frequency_to_bit(frequency):
    if abs(frequency - F_0) < epsilon:
        return '0'
    elif abs(frequency - F_1) < epsilon:
        return '1'
    elif abs(frequency - F_NULL) < epsilon:
        return '#'
    else:
        return None

def receive_signal(duration): # This function used for detecting the messages sent i.e it receives the audio signals from the medium
    p = pyaudio.PyAudio()
    stream = p.open(format=FORMAT, channels=CHANNELS, rate=FS, input=True, frames_per_buffer=CHUNK)

    print("Receiving signal...")
    start_time = time.time()
    received_bits = []
    a = 0
    b = 0
    c = 0
    while (True):
        data = stream.read(CHUNK)

        signal = np.frombuffer(data, dtype=np.float32)

        sig = np.frombuffer(stream.read(CHUNK),dtype = np.float32)
       
        detected_freq = detect_frequency(signal)
       
        bit = frequency_to_bit(detected_freq)
        if bit == '#' and b == 0:
            b = 1
        if b == 1 and (bit == '1' or bit == '0'):
            c = 1
        if bit != None:
            a = 0
            received_bits.append(bit)
        else:
            a = a+1
        print(f"Received bit: {bit}, {detected_freq}")
        if a == 15 or (c == 1 and bit == '#'):
            break
        
    stream.stop_stream()
    stream.close()
    p.terminate()

    received_bits = ''.join(received_bits)

    i = 0
    start = 0
    end = 0

    while i < len(received_bits): # used to extract the bit string excluding #'s from the transmitted message.
        if received_bits[i] != '#':
            i = i + 1
            continue
        while(i < len(received_bits) and received_bits[i] == '#'):
            i = i+1
        start = i
        while(i < len(received_bits) and received_bits[i] != '#'):
            i = i + 1
        end = i
        break

    result = received_bits[start:end]

    return result

def receive_signal_0(duration): # This function carrier senses the medium for the mentioned duration
    p = pyaudio.PyAudio()
    stream = p.open(format=FORMAT, channels=CHANNELS, rate=FS, input=True, frames_per_buffer=CHUNK)

    print("Receiving signal...")
    start_time = time.time()
    received_bits = []
    while (time.time() - start_time < duration):
        data = stream.read(CHUNK)

        signal = np.frombuffer(data, dtype=np.float32)

        sig = np.frombuffer(stream.read(CHUNK),dtype = np.float32)
       
        detected_freq = detect_frequency(signal)
       
        bit = frequency_to_bit(detected_freq)
        if bit != None:
            received_bits.append(bit)
        print(f"Received bit: {bit}, {detected_freq}")
        
    stream.stop_stream()
    stream.close()
    p.terminate()

    received_bits = ''.join(received_bits)

    # i = 0
    # start = 0
    # end = 0

    # while i < len(received_bits): # used to extract the bit string excluding #'s from the transmitted message.
    #     if received_bits[i] != '#':
    #         i = i + 1
    #         continue
    #     while(i < len(received_bits) and received_bits[i] == '#'):
    #         i = i+1
    #     start = i
    #     while(i < len(received_bits) and received_bits[i] != '#'):
    #         i = i + 1
    #     end = i
    #     break

    # result = received_bits[start:end]

    return received_bits
# Shared resource to simulate the busy state of the channel

def is_channel_busy():##Used for carrier sensing the medium for 2 secs
    print("sender CS")
    received_signal = receive_signal_0(2)
    return bool(received_signal)

def send_audio(message):##Used for sending the data_bits using audio medium and we added # for reducing bit errors
    bit_sequence = "######" + message + "######"

    p = pyaudio.PyAudio()
    stream = p.open(format=FORMAT, channels=CHANNELS, rate=FS, output=True, frames_per_buffer=CHUNK)

    t = np.linspace(0, DURATION_PER_BIT, int(FS * DURATION_PER_BIT), endpoint=False)


    for bit in bit_sequence:
        if bit == '0':
       
            tone = 0.5 * np.sin(2 * np.pi * F_0 * t)
        elif bit == '#':

            tone = 0.5 * np.sin(2 * np.pi * F_NULL * t)
        else:
       
            tone = 0.5 *np.sin(2 * np.pi * F_1 * t)
       
        tone = tone.astype(np.float32)
        stream.write(tone.tobytes())

        tone = 0.0 * np.sin(2 * np.pi * 500 * t)
        tone = tone.astype(np.float32)
        stream.write(tone.tobytes())

    stream.stop_stream()
    stream.close()
    p.terminate()

class Node: ##We are using Class Node for initialization , and for handling multiple nodes
    def __init__(self, node_id, messages, destinations):##For initialization of the Node having node_id,message_queue,destiantion_queue
        self.node_id = node_id
        self.message_queue = Queue()
        self.destination_queue = Queue()
        for msg in messages:
            self.message_queue.put(msg)
        for dest in destinations:
            self.destination_queue.put(dest)
        self.received_messages = []

    def create_mac_header(self, message_type, sender_id, receiver_id, data=None):#creates mac_header distinguishing data_types rts , cts , message
        header = f"{message_type}{format(sender_id, '02b')}{format(receiver_id, '02b')}"
        if data:
            return header + data
        return header

    def send_rts(self, destination_id):#sending rts to destination_id
        if is_channel_busy():
            print(f"Node {self.node_id}: Channel is busy, cannot send RTS.")
            return False
        # sleep_time = random.uniform(1, 5)
        # print(f"wait for {sleep_time} sec before sending RTS")
        # time.sleep(sleep_time)
        rts_message = self.create_mac_header('00', self.node_id, destination_id)
        print(f"Node {self.node_id}: Sending RTS to Node {destination_id}. RTS message: {rts_message}")
        send_audio(rts_message)

        return True

    def receive_rts(self):
        final = receive_signal(4)
        if len(final) == 6:
            first_two_bits = final[:2]
            middle_two_bits = final[2:4]
            last_two_bits = final[-2:]

            print(f"Node {self.node_id}: Received RTS from Node {int(middle_two_bits, 2)}. Checking for collision...")

            if first_two_bits == '00':
                last_two_decimal = int(last_two_bits, 2)

                if last_two_decimal == self.node_id or last_two_decimal == 0: ## Checks if the last two bits matches with the node_id || handled case of broadcasting 
                    if last_two_bits != middle_two_bits and int(middle_two_bits, 2) != self.node_id: ## For Handling the case, not sending cts to current node after receiving the rts 
                        print(f"Node {self.node_id}: No collision detected. Sending CTS.")
                        self.send_cts(int(middle_two_bits, 2))
                        # time.sleep(3) ###### not receiver, sender should sleep #######
                        return True
            else:
                # time.sleep(3) ###### not receiver, sender should sleep #######
                return False
        else:
            print(f"Node {self.node_id}: Collision detected. Not sending CTS.")
            return False

    def send_cts(self, source_id):##sending cts to source_id
        cts_message = self.create_mac_header('01', self.node_id, source_id)
        print(f"Node {self.node_id}: Sending CTS to Node {source_id}. CTS message: {cts_message}")
        send_audio(cts_message)

        return True
       
    def receive_cts(self):##Receive Cts
        final = receive_signal(4)
        if len(final) == 6:
            first_two_bits = final[:2]
            middle_two_bits = final[2:4]
            last_two_bits = final[-2:]

            print(f"Node {self.node_id}: Listening for CTS from Node {int(middle_two_bits,2)}...")

            if first_two_bits == '01':
                last_two_decimal = int(last_two_bits, 2)

                if last_two_decimal == self.node_id:
                    if last_two_decimal != middle_two_bits:
                        print(f"Node {self.node_id}: Received CTS.")
                        return True
            else:
                time.sleep(3)
                return False
        else:
            print(f"Node {self.node_id}: Collision detected. Not received CTS.")
            return False

    def send_data(self, destination_id, message): #Sending message to destination_id
        data_message = self.create_mac_header('10', self.node_id, destination_id, message) ##Used first two bits '10' for detecting the message type
        print(f"Node {self.node_id}: Transmitting data '{message}' to Node {destination_id}. Data message: {data_message}")
        send_audio(data_message)

        return True

    def receive_data(self):# Receives data from the node sending rts.
        data_received = receive_signal(8)
        if len(data_received) > 8:
            first_two_bits = data_received[:2] #Extracts first two bits
            middle_two_bits = data_received[2:4] #Extracts middle two bits
            source_id = int(middle_two_bits,2) #Extracts node_id of sender
            message = data_received[6:]
            print(f"[RECVD] {message} {source_id} {datetime.now()}")

            if first_two_bits == '10':
                print(f"Node {self.node_id}: Data received from Node {source_id}.")
                # self.send_ack(self,source_id)
                return True
        else:
            print(f"Node {self.node_id}: Wrong Data received. Collision likely occurred.")
            return False

    # def send_ack(self, source_id):
    #     ack_message = self.create_mac_header('11', self.node_id, source_id)
    #     print(f"Node {self.node_id}: Sending ACK to Node {source_id}. ACK message: {ack_message}")
    #     send_audio(ack_message)

    #     return True
       
    # def receive_ack(self):
    #     print(f"Node {self.node_id}: Waiting for ACK from Node {source.node_id}...")
    #     ack_received = random.choice([True, False])
    #     if ack_received:
    #         print(f"Node {self.node_id}: ACK received from Node {source.node_id}.")
    #         return True
    #     else:
    #         print(f"Node {self.node_id}: No ACK received. Collision likely occurred.")
    #         return False

def sender_thread(node, message_trigger_queue, destination_trigger_queue):
    while True:
        if not message_trigger_queue.empty():
            message = message_trigger_queue.queue[0] ## Taking the first message from the queue
            receiver = destination_trigger_queue.queue[0] ## Taking the first destination from the queue

            if receiver == -1: #No need to send the message
                data = message_trigger_queue.get() #Popping of the message from the queue
                dest = destination_trigger_queue.get() #Popping of the destination from the queue
                continue

            while True:
                if is_channel_busy(): ## Carrier Sensing 
                    print(f"Node {node.node_id}: Channel is busy, waiting...")
                    time.sleep(0.5)
                else:
                    break
               
            if node.send_rts(receiver):
                if not node.receive_cts():
                    backoff_time = random.uniform(1, 5) ## Setting random back-off time
                    print(f"Node {node.node_id}: Backing off for {backoff_time:.2f} seconds.")
                    time.sleep(backoff_time)
                    continue

                node.send_data(receiver, message) # Sending data message to the destination node

                # if not node.receive_ack():
                #     backoff_time = random.uniform(1, 3)
                #     print(f"Node {node.node_id}: No ACK received, backing off for {backoff_time:.2f} seconds.")
                #     time.sleep(backoff_time)
                #     continue

                # else:
                data = message_trigger_queue.get() #popping of the message
                dest = destination_trigger_queue.get()
    # time.sleep(1)

def receiver_thread(node):
    while True: #Infinite loop
        print(f"Node {node.node_id}: Listening for RTS...")
        if node.receive_rts():

            if node.receive_data():
                data_message = "Simulated Data"

        # time.sleep(1)

def input_listener(node, message_trigger_queue, destination_trigger_queue):
    while True:
        input()
        print("Enter pressed inorder to trigger a message sending event...")
        if not node.message_queue.empty(): ## If message queue is not empty
            message = node.message_queue.get()
            destination = node.destination_queue.get()
            print(f"[SENT]: {message} {destination} {datetime.now()}") ## Given trigger and this thread prints out the current time stamp
            message_trigger_queue.put(message)
            destination_trigger_queue.put(destination)

node_0 = Node(2, ["10100101111000", "1111110101"],[1, 1]) ## Maintains current node MAC address and messages

message_trigger_queue_0 = Queue()
destination_trigger_queue_0 = Queue()

##Our code maintains three threads ,it's like mixed processing (concurrent || parallel) execution of sender , receiver and input_listener threads.

sender_thread_0 = threading.Thread(target=sender_thread, args=(node_0, message_trigger_queue_0, destination_trigger_queue_0), daemon=True)
sender_thread_0.start()  ##Taken syntax of threading from Chatgpt

receiver_thread_1 = threading.Thread(target=receiver_thread, args=(node_0,), daemon=True)
receiver_thread_1.start() ##Taken syntax of threading from Chatgpt

input_thread_0 = threading.Thread(target=input_listener, args=(node_0, message_trigger_queue_0, destination_trigger_queue_0), daemon=True)
input_thread_0.start() ### Used for detection of trigger

while True: ## For Keeping main thread alive 
    time.sleep(1)
